name: Deploy (Self-hosted)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Run tests
        run: go test -v ./...

      - name: Backup SQLite (optional)
        run: |
          set -euo pipefail
          [ -d /root/vpnbot/data ] && cp -r /root/vpnbot/data "/root/vpnbot/data_backup_$(date +%F_%H-%M-%S)" || true

      - name: Sync repo into /root/vpnbot (keep data/)
        run: |
          set -euo pipefail
          rsync -a --delete \
            --exclude 'data' --exclude 'data_backup*' \
            --exclude '.git' --exclude 'bot' \
            ./ /root/vpnbot/

      - name: Build bot into /root/vpnbot
        run: |
          set -euo pipefail
          go build -o /root/vpnbot/bot cmd/api/main.go
          chmod +x /root/vpnbot/bot

      - name: Who am I / paths
        run: |
          set -euo pipefail
          whoami
          id
          echo "systemctl path: $(command -v systemctl)"
          ls -l /etc/sudoers.d || true
          sudo -n -l || true

      - name: Restart service (no TTY)
        run: |
          set -euo pipefail
          sudo -n systemctl daemon-reload
          sudo -n systemctl restart vpnbot.service
          sleep 2
          sudo -n systemctl --no-pager -l status vpnbot.service
